CREATE TABLE IF NOT EXISTS log_acessos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tipo TEXT NOT NULL DEFAULT 'LOGIN',
  usuario_id INTEGER,
  usuario_nome TEXT NOT NULL,
  usuario_email TEXT NOT NULL,
  papel TEXT NOT NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE usuarios ADD COLUMN aluno_id INTEGER;
